# CMP 262 Project 1

## Fall 2026 Survey Data Cleaning with pandas

**Student name:**  Giovannie Henderson
**Date:**  10/06/2026

### Purpose
In your own words, explain the overall purpose of this notebook and what you are preparing the data for.

## Before You Begin

This notebook is a guide, not a completed solution. Read each section, write your own pandas code in the empty code cells, run the cells, and explain important decisions in Markdown. Do not manually edit the original CSV files.

## 1 Import pandas

Import pandas using the standard alias used in class.

In [189]:
import pandas as pd

## 2 Load the two survey files

Use pandas to read both CSV files from the `data` folder. Store each survey in its own clearly named DataFrame.

Files:
- `Majors Survey Results - Fall 2026.csv`
- `Non-Majors Survey Results - Fall 2026.csv`

In [190]:
majors_survey = pd.read_csv("data/Majors Survey Results - Fall 2026.csv")
non_majors_survey = pd.read_csv("data/Non-Majors Survey Results - Fall 2026.csv")

## 3 Confirm that both files loaded correctly

Display a small number of rows from each DataFrame. Check the number of rows and columns. Write a short observation below the output.

In [191]:
majors_survey.head()

,Timestamp,Which course are you enrolled in?,How did you hear about County College of Morris? [CCM Web site],How did you hear about County College of Morris? [Social Media],How did you hear about County College of Morris? [Community Event],How did you hear about County College of Morris? [Family member or friend],How did you hear about County College of Morris? [Current CCM student],How did you hear about County College of Morris? [CCM Alumni],How did you hear about County College of Morris? [High School Teacher],How did you hear about County College of Morris? [High School Counselor],...,Did you receive information about the CCM computing programs from any of the following sources? [Employer],Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development],Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program],Did you receive information about the CCM computing programs from any of the following sources? [Other],"Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.","On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?",Please explain your answer to the question above. Why or why not would you be interested in taking another computing class?,Gender,Race/ethnicity,Age
0,2026/09/13 8:33:53 PM AST,CMP 130 Intro to IT,No,No,No,Yes,No,No,Yes,Yes,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,18 and younger
1,2026/09/14 4:32:00 AM AST,CMP 130 Intro to IT,No,No,Yes,Yes,No,Yes,No,No,...,No,Yes,Yes,Don't recall,Criminal Sceince,NaN,NaN,Man,White/Caucasian,35-64
2,2026/09/14 9:45:47 AM AST,CMP 130 Intro to IT,Yes,No,Yes,Yes,No,No,Yes,Yes,...,Don't recall,Don't recall,Don't recall,Don't recall,First Choice,NaN,NaN,Man,Multi-Racial,18 and younger
3,2026/09/14 9:47:56 AM AST,CMP 130 Intro to IT,No,No,No,Yes,Yes,No,No,No,...,No,No,No,No,Engineering,NaN,NaN,Man,Hispanic or Latino,21-24
4,2026/09/14 10:00:59 AM AST,CMP 130 Intro to IT,No,No,No,Yes,No,No,No,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,19-20

In [192]:
non_majors_survey.head()

,Timestamp,Which course are you currently enrolled in?,What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking],What motivated you to seek a computing class at CCM? [To keep current in computing skills],What motivated you to seek a computing class at CCM? [Career Advancement],What motivated you to seek a computing class at CCM? [Career Change],What motivated you to seek a computing class at CCM? [Professional Development],What motivated you to seek a computing class at CCM? [Job Displacement],What motivated you to seek a computing class at CCM? [Relocation],What motivated you to seek a computing class at CCM? [IT Industry Certifications],...,"If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]","If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]","If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]",Gender,Race/ethnicity,Age
0,2026/09/15 10:07:47 AM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Woman,White/Caucasian,18 and younger
1,2026/09/15 2:30:59 PM AST,CMP 126 Computer Technology and Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,Yes,No,Non-binary,Choose not to reply,18 and younger
2,2026/09/15 6:45:11 PM AST,CMP 126 Computer Technology and Applications,Yes,Yes,No,No,Yes,No,No,No,...,Yes,No,Yes,No,No,No,No,Woman,Asian,19-20
3,2026/09/15 6:59:56 PM AST,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,...,Yes,No,No,No,No,Yes,No,Woman,Hispanic or Latino,21-24
4,2026/09/15 7:00:28 PM AST,CMP 135 Computer Concepts with Applications,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,Man,White/Caucasian,18 and younger

### Your observation

Write what you learned about the size and general structure of the two datasets.

## 4 Explore the datasets

Use separate cells to examine each item below for both DataFrames:

- Column names
- Data types and general information
- Summary statistics where appropriate
- Missing-value counts
- Duplicate rows
- Counts for important categorical columns

Do not place all exploration in one large cell.

In [193]:
#Cell 1: column names 

print("Majors columns :")
print(majors_survey.columns.tolist())

print("Non-majors columns:")
print(non_majors_survey.columns.tolist())

Majors columns :
['Timestamp', 'Which course are you enrolled in?', 'How did you hear about County College of Morris? [CCM Web site]', 'How did you hear about County College of Morris? [Social Media]', 'How did you hear about County College of Morris? [Community Event]', 'How did you hear about County College of Morris? [Family member or friend]', 'How did you hear about County College of Morris? [Current CCM student]', 'How did you hear about County College of Morris? [CCM Alumni]', 'How did you hear about County College of Morris? [High School Teacher]', 'How did you hear about County College of Morris? [High School Counselor]', 'How did you hear about County College of Morris? [In-app advertisement]', 'How did you hear about County College of Morris? [Employer]', 'How did you hear about County College of Morris? [Billboard]', 'How did you hear about County College of Morris? [Television]', 'How did you hear about County College of Morris? [Radio]', 'How did you hear about County College of Morris? [Other]', 'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]', 'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]', 'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]', 'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]', 'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]', 'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]', 'To what extent did the following impact your decision to attend County College of Morris? [College reputation]', 'To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]', 'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]', 'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]', 'To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]', 'To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]', 'To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]', 'To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]', 'To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]', 'To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]', 'What degree program are you currently enrolled in?', 'What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]', "What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]", 'What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]', 'What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]', 'What motivated you to seek a computing degree/certificate at CCM?  [Career Change]', 'What motivated you to seek a computing degree/certificate at CCM?  [Professional Development]', 'What motivated you to seek a computing degree/certificate at CCM?  [Job Displacement]', 'What motivated you to seek a computing degree/certificate at CCM?  [Relocation]', 'What motivated you to seek a computing degree/certificate at CCM?  [To keep current in tech industry]', 'What motivated you to seek a computing degree/certificate at CCM?  [IT Industry Certifications]', 'What motivated you to seek a computing degree/certificate at CCM?  [Financial]', 'What motivated you to seek a computing degree/certificate at CCM?  [Personal Enrichment]', 'Did you receive information about the CCM computing programs from any of the following sources? [High school guidance counselor]', 'Did you receive information about the CCM computing programs from any of the following sources? [High School Teacher]', 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Information Technologies Website]', 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Admissions]', 'Did you receive information about the CCM computing programs from any of the following sources? [CCM advisor/counselor]', 'Did you receive information about the CCM computing programs from any of the following sources? [Employer]', 'Did you receive information about the CCM computing programs from any of the following sources? [CCM Workforce Development]', 'Did you receive information about the CCM computing programs from any of the following sources? [NJ Workforce Development Program]', 'Did you receive information about the CCM computing programs from any of the following sources? [Other]', 'Was a computing major/certificate your first choice, or did you change majors from a different CCM program? If you changed majors, indicate what your first major was.', 'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?', 'Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?', 'Gender', 'Race/ethnicity', 'Age ']
Non-majors columns:
['Timestamp', 'Which course are you currently enrolled in?', 'What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking]', 'What motivated you to seek a computing class at CCM? [To keep current in computing skills]', 'What motivated you to seek a computing class at CCM? [Career Advancement]', 'What motivated you to seek a computing class at CCM? [Career Change]', 'What motivated you to seek a computing class at CCM? [Professional Development]', 'What motivated you to seek a computing class at CCM? [Job Displacement]', 'What motivated you to seek a computing class at CCM? [Relocation]', 'What motivated you to seek a computing class at CCM? [IT Industry Certifications]', 'What motivated you to seek a computing class at CCM? [Financial]', 'What motivated you to seek a computing class at CCM? [Personal Enrichment]', 'What motivated you to seek a computing class at CCM? [Curiosity]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]', "Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [TItan's Tuesday Virtual Information Session]", 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]', 'Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]', 'To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]', 'How did you hear about County College of Morris  [CCM Web site]', 'How did you hear about County College of Morris  [Billboard]', 'How did you hear about County College of Morris  [Television]', 'How did you hear about County College of Morris  [Radio]', 'How did you hear about County College of Morris  [Social Media]', 'How did you hear about County College of Morris  [Community Event]', 'How did you hear about County College of Morris  [Family member or friend]', 'How did you hear about County College of Morris  [Employer]', 'How did you hear about County College of Morris  [Current student]', 'How did you hear about County College of Morris  [Alumni]', 'How did you hear about County College of Morris  [High School]', 'To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]', 'To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]', 'To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]', 'To what extent did the following impact your decision to attend County College of Morris? [Online offerings]', 'To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]', 'To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]', 'To what extent did the following impact your decision to attend County College of Morris? [College reputation]', 'To what extent did the following impact your decision to attend County College of Morris? [Scholarships]', 'To what extent did the following impact your decision to attend County College of Morris? [Transfer student]', 'To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]', 'To what extent did the following impact your decision to attend County College of Morris? [Extra curricula opportunities]', 'What degree program are you currently enrolled in?', 'Did you receive information about our computing course from any of the following sources? [High school guidance counselor]', 'Did you receive information about our computing course from any of the following sources? [CCM Information Technologies Website]', 'Did you receive information about our computing course from any of the following sources? [CCM Admissions]', 'Did you receive information about our computing course from any of the following sources? [CCM advisor/counselor]', 'Did you receive information about our computing course from any of the following sources? [Employer]', 'Did you receive information about our computing course from any of the following sources? [Other]', 'On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Web Development]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [CyberSecurity]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [App Development]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Data Analytics]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Machine Learning/Artificial Intelligence]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Computer Programming]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]', 'If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]', 'Gender', 'Race/ethnicity', 'Age ']

In [194]:
# Cell 2: data types and general info 

majors_survey.info()
non_majors_survey.info()

<class 'pandas.DataFrame'>
RangeIndex: 173 entries, 0 to 172
Data columns (total 90 columns):
 #   Column                                                                                                                                                                                                                                                           Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                           --------------  -----
 0   Timestamp                                                                                                                                                                                                                                                        173 non-null    str
 1   Which course are you enrolled in?                                                                                                                                                                                                                                173 non-null    str
 2   How did you hear about County College of Morris? [CCM Web site]                                                                                                                                                                                                  173 non-null    str
 3   How did you hear about County College of Morris? [Social Media]                                                                                                                                                                                                  173 non-null    str
 4   How did you hear about County College of Morris? [Community Event]                                                                                                                                                                                               173 non-null    str
 5   How did you hear about County College of Morris? [Family member or friend]                                                                                                                                                                                       173 non-null    str
 6   How did you hear about County College of Morris? [Current CCM student]                                                                                                                                                                                           173 non-null    str
 7   How did you hear about County College of Morris? [CCM Alumni]                                                                                                                                                                                                    173 non-null    str
 8   How did you hear about County College of Morris? [High School Teacher]                                                                                                                                                                                           173 non-null    str
 9   How did you hear about County College of Morris? [High School Counselor]                                                                                                                                                                                         173 non-null    str
 10  How did you hear about County College of Morris? [In-app advertisement]                                                                                                                                                                                          173 non-null    str
 11  How did you hear about County College of Morris? [Employer]                                                                                                                                                                                                      173 non-null    str
 12  How did you hear about County College of Morris? [Billboard]                                                                                                                                                                                                     173 non-null    str
 13  How did you hear about County College of Morris? [Television]                                                                                                                                                                                                    173 non-null    str
 14  How did you hear about County College of Morris? [Radio]                                                                                                                                                                                                         173 non-null    str
 15  How did you hear about County College of Morris? [Other]                                                                                                                                                                                                         173 non-null    str
 16  To what extent did the following impact your decision to attend County College of Morris? [Affordable cost]                                                                                                                                                      146 non-null    str
 17  To what extent did the following impact your decision to attend County College of Morris? [Location/convenience]                                                                                                                                                 164 non-null    str
 18  To what extent did the following impact your decision to attend County College of Morris? [Choice of programs]                                                                                                                                                   163 non-null    str
 19  To what extent did the following impact your decision to attend County College of Morris? [Online offerings]                                                                                                                                                     148 non-null    str
 20  To what extent did the following impact your decision to attend County College of Morris? [Family/friend referral]                                                                                                                                               147 non-null    str
 21  To what extent did the following impact your decision to attend County College of Morris? [Faculty/staff]                                                                                                                                                        143 non-null    str
 22  To what extent did the following impact your decision to attend County College of Morris? [College reputation]                                                                                                                                                   151 non-null    str
 23  To what extent did the following impact your decision to attend County College of Morris? [Financial Aid]                                                                                                                                                        137 non-null    str
 24  To what extent did the following impact your decision to attend County College of Morris? [Scholarships]                                                                                                                                                         135 non-null    str
 25  To what extent did the following impact your decision to attend County College of Morris? [Small class sizes]                                                                                                                                                    149 non-null    str
 26  To what extent did the following impact your decision to attend County College of Morris? [Extra-curricular opportunities]                                                                                                                                       146 non-null    str
 27  To what extent did the following impact your decision to attend County College of Morris? [Accepted my transfer credits]                                                                                                                                         125 non-null    str
 28  To what extent did the following impact your decision to attend County College of Morris? [Negative experience at another college]                                                                                                                               113 non-null    str
 29  To what extent did the following impact your decision to attend County College of Morris? [NJ Stars Program]                                                                                                                                                     113 non-null    str
 30  To what extent did the following impact your decision to attend County College of Morris? [Ability to transfer CCM credits to a 4-year school]                                                                                                                   158 non-null    str
 31  To what extent did the following impact your decision to attend County College of Morris? [Get college credit while in high school]                                                                                                                              130 non-null    str
 32  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Open House]                                                   173 non-null    str
 33  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Instant Decision Day]                                         173 non-null    str
 34  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [On-Campus Information Session]                                173 non-null    str
 35  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Titans Tuesday (Virtual) Information Session]                 173 non-null    str
 36  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Women Who Dare]                                               173 non-null    str
 37  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Regional College Fair]                                        173 non-null    str
 38  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [HS Sharetime Information Session]                             173 non-null    str
 39  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Challenger Program]                                           173 non-null    str
 40  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [CyberSecurity Information Protection Program Participation ]  173 non-null    str
 41  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Information Session at my high school]                        173 non-null    str
 42  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit with my high school]                             173 non-null    str
 43  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Campus Visit (individual)]                                    173 non-null    str
 44  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Workforce Development class]                                  173 non-null    str
 45  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Corporate Training]                                           173 non-null    str
 46  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Teen Arts Festival]                                           173 non-null    str
 47  Prior to applying to college, did you participate in any of the following events or activities at the County College of Morris and/or with the Department of Information Technologies, if at all? [Summer camp at CCM]                                           173 non-null    str
 48  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing class]                                                                                                     143 non-null    str
 49  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Middle/High school computing related club]                                                                                              125 non-null    str
 50  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Computing-related competitions (e.g., Robotics competition, Lego competition, Cybersecurity, Programming)]                              131 non-null    str
 51  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Afterschool computing-related camp/program]                                                                                             120 non-null    str
 52  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Summer computing related camp/program]                                                                                                  118 non-null    str
 53  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [An AP computing class]                                                                                                                  121 non-null    str
 54  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [A dual enrollment computing class]                                                                                                      120 non-null    str
 55  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend influence]                                                                                                             143 non-null    str
 56  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Family or friend working in the computing field]                                                                                        134 non-null    str
 57  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [High school teacher or guidance counselor]                                                                                              132 non-null    str
 58  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Employer influence]                                                                                                                     124 non-null    str
 59  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Current CCM student]                                                                                                                    132 non-null    str
 60  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Experience at work]                                                                                                                     131 non-null    str
 61  To what extent did the following activities or experience impact your decision to enroll in an computing course at CCM? [Other]                                                                                                                                  112 non-null    str
 62  What degree program are you currently enrolled in?                                                                                                                                                                                                               173 non-null    str
 63  What motivated you to seek a computing degree/certificate at CCM?  [To get a job in the computing field]                                                                                                                                                         114 non-null    str
 64  What motivated you to seek a computing degree/certificate at CCM?  [Transfer to bachelor's level program]                                                                                                                                                        114 non-null    str
 65  What motivated you to seek a computing degree/certificate at CCM?  [Transfer credits back to HS degree (ShareTime, Challenger Program)]                                                                                                                          114 non-null    str
 66  What motivated you to seek a computing degree/certificate at CCM?  [Career Advancement]                                                                                                                                                                          114 non-null    str
 67  What motivated you to seek a computing degree/certificate at CCM?  [Career Change]                                                                                                                                                                               114 non-null    str

In [195]:
#cell 3: summary statistics 

majors_survey.describe()
non_majors_survey.describe()

       On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you taking more courses in Computer Science, Information Technology or Game Development?
count                                         118.000000
mean                                            2.254237
std                                             1.055603
min                                             1.000000
25%                                             1.000000
50%                                             2.000000
75%                                             3.000000
max                                             5.000000

In [196]:
# Cell 4: missing values and duplicate rows 

print("Majors missing values:")
print(majors_survey.isna().sum())

print("Non-Majors missing values:")
print(non_majors_survey.isna().sum())

print("Majors duplicate rows:", majors_survey.duplicated().sum())
print("Non-Majors duplicate rows:", non_majors_survey.duplicated().sum())

Majors missing values:
Timestamp                                                                                                                                                0
Which course are you enrolled in?                                                                                                                        0
How did you hear about County College of Morris? [CCM Web site]                                                                                          0
How did you hear about County College of Morris? [Social Media]                                                                                          0
How did you hear about County College of Morris? [Community Event]                                                                                       0
                                                                                                                                                      ...
On a scale of 1 to 5, with 1 being not at all interested and 5 being extremely interested, how interested are you in taking more computing classes?    114
Please explain your answer to the question above.  Why or why not would you be interested in taking another computing class?                           114
Gender                                                                                                                                                   0
Race/ethnicity                                                                                                                                           0
Age                                                                                                                                                      0
Length: 90, dtype: int64
Non-Majors missing values:
Timestamp                                                                                                                                    0
Which course are you currently enrolled in?                                                                                                  0
What motivated you to seek a computing class at CCM? [Itâ€™s a required class for the degree Iâ€™m seeking]                                  0
What motivated you to seek a computing class at CCM? [To keep current in computing skills]                                                   0
What motivated you to seek a computing class at CCM? [Career Advancement]                                                                    0
                                                                                                                                            ..
If you answered that you were interested in taking more computing classes, which ones interest you most? [Game Design]                       0
If you answered that you were interested in taking more computing classes, which ones interest you most? [Hardware Installation & Repair]    0
Gender                                                                                                                                       1
Race/ethnicity                                                                                                                               0
Age                                                                                                                                          0
Length: 71, dtype: int64
Majors duplicate rows: 0
Non-Majors duplicate rows: 0

### Exploration findings

Describe at least three important issues or patterns you discovered.

1. In the majors survey, the interest in more computing classes question and its follow-up each have 114 missing responses.
2. In the non-majors survey, the gender column has one missing response.
3. Neither dataset has duplicate rows.

## 5 Clean the column names

Rename the columns so they are clear, lowercase, and use underscores between words when needed. Make sure the final column names are unique.

Show the column names before and after cleaning.

In [209]:
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]": "How did you hear about CCM? (CCM Website)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[social_media]": "How did you hear about CCM? (Social Media)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[community_event]": "How did you hear about CCM? (Community Event)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]": "How did you hear about CCM? (Family Member/Friend)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]": "How did you hear about CCM? (Current CCM Student)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]": "How did you hear about CCM? (CCM Alumni)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]": "How did you hear about CCM? (High School Teacher)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]": "How did you hear about CCM? (High Scchool Counselor)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]": "How did you hear about CCM? (in-app_advertisement)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[employer]": "How did you hear about CCM? (Employer)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[billboard]": "How did you hear about CCM? (Billboard)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[television]": "How did you hear about CCM? (Television)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[radio]": "How did you hear about CCM? (Radio)"})
majors_survey = majors_survey.rename(columns={"how_did_you_hear_about_county_college_of_morris?_[other]": "How did you hear about CCM? (Other)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]": "Impact on CCM Decision (Affordable Cost)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]": "Impact on CCM Decision (Location/Convience)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]": "Impact on CCM Decision (Choice of Programs)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]": "Impact on CCM Decision (Online Offerings)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]": "Impact on CCM Decision (Family/Friend Referral)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]": "Impact on CCM Decision (Faculty/Staff)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]": "Impact on CCM Decision (College Reputation)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]": "Impact on CCM Decision (Financial Aid)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]": "Impact on CCM Decision (Scholarships)"})
majors_survey = majors_survey.rename(columns={"to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]": "Impact on CCM Decision (Small Class Sizes)"})

In [210]:
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]": "Why take a computing class at CCM? [Required for my degree]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]": "Why take a computing class at CCM? [to Keep Current in Compting Skills]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]": "Why take a computing class at CCM? [Career Advancemnt]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]": "Why take a computing class at CCM? [Career Change]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]": "Why take a computing class at CCM? [Professional Development]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]": "Why take a computing class at CCM? [Job Displacement]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]": "Why take a computing class at CCM? [Relocation]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]": "Why take a computing class at CCM? [it Industry Certification]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]": "Why take a computing class at CCM? [Financial]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]": "Why take a computing class at CCM? [Personal Enrichment]"})
non_majors_survey = non_majors_survey.rename(columns={"what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]": "Why take a computing class at CCM? [Curiosity]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]": "Did you attend any CCM events before applying? [Open house]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]": "Did you attend any CCM events before applying? [Instant Decision Day]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]": "Did you attend any CCM events before applying? [On-Campus Information Session]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]": "Did you attend any CCM events before applying? [Titan's Tuesday Virtual Information Session]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]": "Did you attend any CCM events before applying? [Women Who Dare]"})
non_majors_survey = non_majors_survey.rename(columns={"prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]": "Did you attend any CCM events before applying? [Regional College Fair]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]": "What impacted your decision to take computing at CCM?[Middle/High School Computing Class]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]": "What impacted your decision to take computing at CCM?[Middle/HighSchool Computing Related Club]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]": "What impacted your decision to take computing at CCM?[Computing Related Competitions (e.g., Robotics Competition, Lego Competition, Cybersecurity, Programming)]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]": "What impacted your decision to take computing at CCM?[afterschool_computing-related Camp/Program]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]": "What impacted your decision to take computing at CCM?[summer_computing_related_camp/program]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]": "What impacted your decision to take computing at CCM?[An Ap Computing Class]"})
non_majors_survey = non_majors_survey.rename(columns={"to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]": "What impacted your decision to take computing at CCM?[A Dual Enrollment Computing Class]"})                                         
non_majors_survey = non_majors_survey.rename(columns={"if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]": "Which computing classes interest you most? [computer_programming]"})
non_majors_survey = non_majors_survey.rename(columns={"if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]": "Which computing classes interest you most? [game_design]"})
non_majors_survey = non_majors_survey.rename(columns={"if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]": "Which computing classes interest you most? [hardware_installation_&_repair]"})

In [212]:
print("Before:", majors_survey.columns)
print("Before Non-Majors", non_majors_survey)


majors_survey.columns = majors_survey.columns.str.strip().str.lower().str.replace(" ", "_")
non_majors_survey.columns = non_majors_survey.columns.str.strip().str.lower().str.replace(" ", "_")


majors_survey.columns
non_majors_survey.columns

Before: Index(['timestamp', 'which_course_are_you_enrolled_in?',
       'how_did_you_hear_about_ccm?_(ccm_website)',
       'how_did_you_hear_about_ccm?_(social_media)',
       'how_did_you_hear_about_ccm?_(community_event)',
       'how_did_you_hear_about_ccm?_(family_member/friend)',
       'how_did_you_hear_about_ccm?_(current_ccm_student)',
       'how_did_you_hear_about_ccm?_(ccm_alumni)',
       'how_did_you_hear_about_ccm?_(high_school_teacher)',
       'how_did_you_hear_about_ccm?_(high_scchool_counselor)',
       'how_did_you_hear_about_ccm?_(in-app_advertisement)',
       'how_did_you_hear_about_ccm?_(employer)',
       'how_did_you_hear_about_ccm?_(billboard)',
       'how_did_you_hear_about_ccm?_(television)',
       'how_did_you_hear_about_ccm?_(radio)',
       'how_did_you_hear_about_ccm?_(other)',
       'impact_on_ccm_decision_(affordable_cost)',
       'impact_on_ccm_decision_(location/convience)',
       'impact_on_ccm_decision_(choice_of_programs)',
       'impact_on_ccm_decision_(online_offerings)',
       'impact_on_ccm_decision_(family/friend_referral)',
       'impact_on_ccm_decision_(faculty/staff)',
       'impact_on_ccm_decision_(college_reputation)',
       'impact_on_ccm_decision_(financial_aid)',
       'impact_on_ccm_decision_(scholarships)',
       'impact_on_ccm_decision_(small_class_sizes)',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')
Before Non-Majors                       timestamp   which_course_are_you_currently_enrolled_in?  \
0    2026/09/15 10:07:47 AM AST  CMP 126 Computer Technology and Applications
1     2026/09/15 2:30:59 PM AST  CMP 126 Computer Technology and Applications
2     2026/09/15 6:45:11 PM AST  CMP 126 Computer Technology and Applications
3     2026/09/15 6:59:56 PM AST   CMP 135 Computer Concepts with Applications
4     2026/09/15 7:00:28 PM AST   CMP 135 Computer Concepts with Applications
..                          ...                                           ...
113  2026/09/26 12:51:06 PM AST  CMP 126 Computer Technology and Applications
114   2026/09/26 7:56:53 PM AST   CMP 135 Computer Concepts with Applications
115   2026/09/27 7:50:41 PM AST         CMP 101 Computer Information Literacy
116   2026/09/28 8:58:59 AM AST   CMP 135 Computer Concepts with Applications
117   2026/09/28 9:25:15 PM AST         CMP 101 Computer Information Literacy

    why_take_a_computing_class_at_ccm?_[required_for_my_degree]  \
0                                                  Yes
1                                                  Yes
2                                                  Yes
3                                                  Yes
4                                                  Yes
..                                                 ...
113                                                Yes
114                                                Yes
115                                                Yes
116                                                Yes
117                                                Yes

    why_take_a_computing_class_at_ccm?_[to_keep_current_in_compting_skills]  \
0                                                   No
1                                                   No
2                                                  Yes
3                                                   No
4                                                   No
..                                                 ...
113                                                Yes
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    why_take_a_computing_class_at_ccm?_[career_advancemnt]  \
0                                                   No
1                                                   No
2                                                   No
3                                                   No
4                                                   No
..                                                 ...
113                                                Yes
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    why_take_a_computing_class_at_ccm?_[career_change]  \
0                                                   No
1                                                   No
2                                                   No
3                                                   No
4                                                   No
..                                                 ...
113                                                 No
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    why_take_a_computing_class_at_ccm?_[professional_development]  \
0                                                   No
1                                                   No
2                                                  Yes
3                                                   No
4                                                   No
..                                                 ...
113                                                Yes
114                                                 No
115                                                 No
116                                                Yes
117                                                 No

    why_take_a_computing_class_at_ccm?_[job_displacement]  \
0                                                   No
1                                                   No
2                                                   No
3                                                   No
4                                                   No
..                                                 ...
113                                                 No
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    why_take_a_computing_class_at_ccm?_[relocation]  \
0                                                No
1                                                No
2                                                No
3                                                No
4                                                No
..                                              ...
113                                              No
114                                              No
115                                              No
116                                              No
117                                              No

    why_take_a_computing_class_at_ccm?_[it_industry_certification]  ...  \
0                                                   No              ...
1                                                   No              ...
2                                                   No              ...
3                                                   No              ...
4                                                   No              ...
..                                                 ...              ...
113                                                 No              ...
114                                                 No              ...
115                                                 No              ...
116                                                 No              ...
117                                                 No              ...

    if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]  \
0                                                   No
1                                                   No
2                                                  Yes
3                                                  Yes
4                                                   No
..                                                 ...
113                                                 No
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]  \
0                                                   No
1                                                   No
2                                                   No
3                                                   No
4                                                   No
..                                                 ...
113                                                Yes
114                                                 No
115                                                 No
116                                                 No
117                                                 No

    if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]  \
0                                                   No
1                                                   No
2                                                  Yes
3                                                   No
4                                                   No
..                                                 ...
113                                                 No
114                                                 No
115                                                 No
116                                                 No
117                                                 No


Index(['timestamp', 'which_course_are_you_currently_enrolled_in?',
       'why_take_a_computing_class_at_ccm?_[required_for_my_degree]',
       'why_take_a_computing_class_at_ccm?_[to_keep_current_in_compting_skills]',
       'why_take_a_computing_class_at_ccm?_[career_advancemnt]',
       'why_take_a_computing_class_at_ccm?_[career_change]',
       'why_take_a_computing_class_at_ccm?_[professional_development]',
       'why_take_a_computing_class_at_ccm?_[job_displacement]',
       'why_take_a_computing_class_at_ccm?_[relocation]',
       'why_take_a_computing_class_at_ccm?_[it_industry_certification]',
       'why_take_a_computing_class_at_ccm?_[financial]',
       'why_take_a_computing_class_at_ccm?_[personal_enrichment]',
       'why_take_a_computing_class_at_ccm?_[curiosity]',
       'did_you_attend_any_ccm_events_before_applying?_[open_house]',
       'did_you_attend_any_ccm_events_before_applying?_[instant_decision_day]',
       'did_you_attend_any_ccm_events_before_applying?_[on-campus_information_session]',
       'did_you_attend_any_ccm_events_before_applying?_[titan's_tuesday_virtual_information_session]',
       'did_you_attend_any_ccm_events_before_applying?_[women_who_dare]',
       'did_you_attend_any_ccm_events_before_applying?_[regional_college_fair]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[middle/high_school_computing_class]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[middle/highschool_computing_related_club]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[computing_related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[afterschool_computing-related_camp/program]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[summer_computing_related_camp/program]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[an_ap_computing_class]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris__[billboard]',
       'how_did_you_hear_about_county_college_of_morris__[television]',
       'how_did_you_hear_about_county_college_of_morris__[radio]',
       'how_did_you_hear_about_county_college_of_morris__[social_media]',
       'how_did_you_hear_about_county_college_of_morris__[community_event]',
       'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris__[employer]',
       'how_did_you_hear_about_county_college_of_morris__[current_student]',
       'how_did_you_hear_about_county_college_of_morris__[alumni]',
       'how_did_you_hear_about_county_college_of_morris__[high_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]',
       'which_computing_classes_interest_you_most?_[computer_programming]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')

### Column-name decisions

Explain the method you used and describe any columns that required special attention.

In [213]:
majors_survey.columns

Index(['timestamp', 'which_course_are_you_enrolled_in?',
       'how_did_you_hear_about_ccm?_(ccm_website)',
       'how_did_you_hear_about_ccm?_(social_media)',
       'how_did_you_hear_about_ccm?_(community_event)',
       'how_did_you_hear_about_ccm?_(family_member/friend)',
       'how_did_you_hear_about_ccm?_(current_ccm_student)',
       'how_did_you_hear_about_ccm?_(ccm_alumni)',
       'how_did_you_hear_about_ccm?_(high_school_teacher)',
       'how_did_you_hear_about_ccm?_(high_scchool_counselor)',
       'how_did_you_hear_about_ccm?_(in-app_advertisement)',
       'how_did_you_hear_about_ccm?_(employer)',
       'how_did_you_hear_about_ccm?_(billboard)',
       'how_did_you_hear_about_ccm?_(television)',
       'how_did_you_hear_about_ccm?_(radio)',
       'how_did_you_hear_about_ccm?_(other)',
       'impact_on_ccm_decision_(affordable_cost)',
       'impact_on_ccm_decision_(location/convience)',
       'impact_on_ccm_decision_(choice_of_programs)',
       'impact_on_ccm_decision_(online_offerings)',
       'impact_on_ccm_decision_(family/friend_referral)',
       'impact_on_ccm_decision_(faculty/staff)',
       'impact_on_ccm_decision_(college_reputation)',
       'impact_on_ccm_decision_(financial_aid)',
       'impact_on_ccm_decision_(scholarships)',
       'impact_on_ccm_decision_(small_class_sizes)',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')

In [215]:
non_majors_survey.columns

Index(['timestamp', 'which_course_are_you_currently_enrolled_in?',
       'why_take_a_computing_class_at_ccm?_[required_for_my_degree]',
       'why_take_a_computing_class_at_ccm?_[to_keep_current_in_compting_skills]',
       'why_take_a_computing_class_at_ccm?_[career_advancemnt]',
       'why_take_a_computing_class_at_ccm?_[career_change]',
       'why_take_a_computing_class_at_ccm?_[professional_development]',
       'why_take_a_computing_class_at_ccm?_[job_displacement]',
       'why_take_a_computing_class_at_ccm?_[relocation]',
       'why_take_a_computing_class_at_ccm?_[it_industry_certification]',
       'why_take_a_computing_class_at_ccm?_[financial]',
       'why_take_a_computing_class_at_ccm?_[personal_enrichment]',
       'why_take_a_computing_class_at_ccm?_[curiosity]',
       'did_you_attend_any_ccm_events_before_applying?_[open_house]',
       'did_you_attend_any_ccm_events_before_applying?_[instant_decision_day]',
       'did_you_attend_any_ccm_events_before_applying?_[on-campus_information_session]',
       'did_you_attend_any_ccm_events_before_applying?_[titan's_tuesday_virtual_information_session]',
       'did_you_attend_any_ccm_events_before_applying?_[women_who_dare]',
       'did_you_attend_any_ccm_events_before_applying?_[regional_college_fair]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[middle/high_school_computing_class]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[middle/highschool_computing_related_club]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[computing_related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[afterschool_computing-related_camp/program]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[summer_computing_related_camp/program]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[an_ap_computing_class]',
       'what_impacted_your_decision_to_take_computing_at_ccm?[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris__[billboard]',
       'how_did_you_hear_about_county_college_of_morris__[television]',
       'how_did_you_hear_about_county_college_of_morris__[radio]',
       'how_did_you_hear_about_county_college_of_morris__[social_media]',
       'how_did_you_hear_about_county_college_of_morris__[community_event]',
       'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris__[employer]',
       'how_did_you_hear_about_county_college_of_morris__[current_student]',
       'how_did_you_hear_about_county_college_of_morris__[alumni]',
       'how_did_you_hear_about_county_college_of_morris__[high_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]',
       'which_computing_classes_interest_you_most?_[computer_programming]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')

## 6 Select useful features

The study focuses on recruitment and enrollment. Decide which columns are useful for that purpose and which are irrelevant or redundant.

Before removing anything:
1. List the columns you plan to keep or remove.
2. Explain your reasoning.
3. Use pandas to create cleaned DataFrames without changing the original DataFrames.

Keep: Course enrollment, how students heard about CCM, reasons for attending, and the demographics.

Remove: Timestamp, because the date and time of each response arent needed for this analysis

### Feature-selection plan

Write your plan and justification here before writing the code.

Keep: Course enrollment, how students heard about CCM, reasons for attending, and the demographics.

Remove: Timestamp, because the date and time of each response arent needed for this analysis

In [202]:
majors_cleaned = majors_survey.drop(columns=["timestamp"])

non_majors_cleaned = non_majors_survey.drop(columns=["timestamp"])

## 7 Clean inconsistent values

Examine important categorical features such as major and race or ethnicity. Look for spelling differences, repeated categories, blank values, or categories that should reasonably be grouped.

Show value counts before and after each important change. Do not combine categories without explaining why.

In [203]:
print(majors_cleaned["race/ethnicity"].value_counts(dropna=False))
print(non_majors_cleaned["race/ethnicity"].value_counts(dropna=False))

race/ethnicity
White/Caucasian                                                                     61
Hispanic or Latino                                                                  37
Asian                                                                               22
Black/African American                                                              18
Hispanic or Latino;White/Caucasian                                                   9
Multi-Racial                                                                         8
Choose not to reply                                                                  8
Hispanic or Latino;Black/African American                                            2
Hispanic or Latino;Asian                                                             2
Hispanic or Latino;American Indian/Native American/Alaska Native;White/Caucasian     1
Asian;White/Caucasian                                                                1
American Indian/Native American/Alaska Native                                        1
White/Caucasian;Multi-Racial                                                         1
Asian;Multi-Racial                                                                   1
Hispanic or Latino;American Indian/Native American/Alaska Native                     1
Name: count, dtype: int64
race/ethnicity
White/Caucasian                                                                                      56
Hispanic or Latino                                                                                   29
Asian                                                                                                 7
Black/African American                                                                                6
Choose not to reply                                                                                   5
Hispanic or Latino;White/Caucasian                                                                    5
American Indian/Native American/Alaska Native;White/Caucasian                                         3
Hispanic or Latino;White/Caucasian;Multi-Racial                                                       3
Native Hawaiian/Other Pacific Islander;White/Caucasian                                                1
Black/African American;White/Caucasian                                                                1
Asian;White/Caucasian                                                                                 1
American Indian/Native American/Alaska Native;Black/African American;White/Caucasian;Multi-Racial     1
Name: count, dtype: int64

### Value-cleaning decisions

Explain what you changed, what you did not change, and why.

The column names were changed to lowercase, extra spaces were removed, and spaces between words were replaced with underscores to make them easier to use. The timestamp column was removed because it wasn’t needed for the recruitment and enrollment analysis. The survey responses and categories have not been changed yet because they need to be checked for inconsistencies first.

## 8 Compare the two surveys

Compare the majors and non-majors column names. Identify:

- Questions or features found in both surveys
- Similar questions with different wording
- Features found in only one survey

Use pandas for the comparison and summarize what you discover.

In [204]:
print("Found in both surveys:")
print(majors_cleaned.columns.intersection(non_majors_cleaned.columns))

print("Only in majors survey:")
print(majors_cleaned.columns.difference(non_majors_cleaned.columns))

print("Only in the non-majors surevey:")
print(non_majors_cleaned.columns.difference(majors_cleaned.columns))

Found in both surveys:
Index(['to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'what_degree_program_are_you_currently_enrolled_in?', 'gender',
       'race/ethnicity', 'age'],
      dtype='str')
Only in majors survey:
Index(['did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'how_did_you_hear_about_county_college_of_morris?_[billboard]',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris?_[community_event]',
       'how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]',
       'how_did_you_hear_about_county_college_of_morris?_[employer]',
       'how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]',
       'how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]',
       'how_did_you_hear_about_county_college_of_morris?_[other]',
       'how_did_you_hear_about_county_college_of_morris?_[radio]',
       'how_did_you_hear_about_county_college_of_morris?_[social_media]',
       'how_did_you_hear_about_county_college_of_morris?_[television]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'which_course_are_you_enrolled_in?'],
      dtype='str')
Only in the non-majors surevey:
Index(['did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
       'how_did_you_hear_about_county_college_of_morris__[alumni]',
       'how_did_you_hear_about_county_college_of_morris__[billboard]',
       'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris__[community_event]',
       'how_did_you_hear_about_county_college_of_morris__[current_student]',
       'how_did_you_hear_about_county_college_of_morris__[employer]',
       'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris__[high_school]',
       'how_did_you_hear_about_county_college_of_morris__[radio]',
       'how_did_you_hear_about_county_college_of_morris__[social_media]',
       'how_did_you_hear_about_county_college_of_morris__[television]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]',
       'which_course_are_you_currently_enrolled_in?'],
      dtype='str')

### Survey comparison

Explain the important similarities and differences between the two surveys.

Both surveys include demographic questions such as age, gender, and race/ethnicity, and both ask about course enrollment and interest in taking more computing classes. Some questions ask the same thing but use different wording. The majors survey includes questions about how students heard about CCM and why they chose to attend, while the non-majors survey asks what motivated students to take a computing class. These differences help explain college enrollment choices and interest in computing courses.

## 9 Validate the cleaned DataFrames

Before saving, verify both cleaned DataFrames. Check their shape, columns, missing values, duplicate rows, data types, and important category values.

If you discover a problem, return to the appropriate cleaning section and correct it.

In [205]:
print("Majors")
print("Shape:", majors_cleaned.shape)
print("Columns:", majors_cleaned.columns)
print("Unique column names:", majors_cleaned.columns.is_unique)
print("Missing values:", majors_cleaned.isna().sum())
print("Duplicate rows:", majors_cleaned.duplicated().sum())
print("Data types:", majors_cleaned.dtypes)
print(majors_cleaned["race/ethnicity"].value_counts(dropna=False))

Majors
Shape: (173, 89)
Columns: Index(['which_course_are_you_enrolled_in?',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris?_[social_media]',
       'how_did_you_hear_about_county_college_of_morris?_[community_event]',
       'how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris?_[current_ccm_student]',
       'how_did_you_hear_about_county_college_of_morris?_[ccm_alumni]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_teacher]',
       'how_did_you_hear_about_county_college_of_morris?_[high_school_counselor]',
       'how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement]',
       'how_did_you_hear_about_county_college_of_morris?_[employer]',
       'how_did_you_hear_about_county_college_of_morris?_[billboard]',
       'how_did_you_hear_about_county_college_of_morris?_[television]',
       'how_did_you_hear_about_county_college_of_morris?_[radio]',
       'how_did_you_hear_about_county_college_of_morris?_[other]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[financial_aid]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra-curricular_opportunities]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[accepted_my_transfer_credits]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[negative_experience_at_another_college]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[nj_stars_program]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[ability_to_transfer_ccm_credits_to_a_4-year_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[get_college_credit_while_in_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titans_tuesday_(virtual)_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[hs_sharetime_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[challenger_program]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[cybersecurity_information_protection_program_participation_]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[information_session_at_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_with_my_high_school]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[campus_visit_(individual)]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[workforce_development_class]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[corporate_training]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[teen_arts_festival]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[summer_camp_at_ccm]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[current_ccm_student]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[experience_at_work]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[other]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_get_a_job_in_the_computing_field]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_to_bachelor's_level_program]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[transfer_credits_back_to_hs_degree_(sharetime,_challenger_program)]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_advancement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[career_change]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[professional_development]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[job_displacement]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[relocation]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[to_keep_current_in_tech_industry]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[financial]',
       'what_motivated_you_to_seek_a_computing_degree/certificate_at_ccm?__[personal_enrichment]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[high_school_teacher]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program]',
       'did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other]',
       'was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?',
       'please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')
Unique column names: True
Missing values: which_course_are_you_enrolled_in?                                                                                                                        0
how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]                                                                                          0
how_did_you_hear_about_county_college_of_morris?_[social_media]                                                                                          0
how_did_you_hear_about_county_college_of_morris?_[community_event]                                                                                       0
how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]                                                                               0
                                                                                                                                                      ...
on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?    114
please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?                           114
gender                                                                                                                                                   0
race/ethnicity                                                                                                                                           0
age                                                                                                                                                      0
Length: 89, dtype: int64
Duplicate rows: 0
Data types: which_course_are_you_enrolled_in?                                                                                                                          str
how_did_you_hear_about_county_college_of_morris?_[ccm_web_site]                                                                                            str
how_did_you_hear_about_county_college_of_morris?_[social_media]                                                                                            str
how_did_you_hear_about_county_college_of_morris?_[community_event]                                                                                         str
how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend]                                                                                 str
                                                                                                                                                        ...
on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?    float64
please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?                               str
gender                                                                                                                                                     str
race/ethnicity                                                                                                                                             str
age                                                                                                                                                        str
Length: 89, dtype: object
race/ethnicity
White/Caucasian                                                                     61
Hispanic or Latino                                                                  37
Asian                                                                               22
Black/African American                                                              18
Hispanic or Latino;White/Caucasian                                                   9
Multi-Racial                                                                         8
Choose not to reply                                                                  8
Hispanic or Latino;Black/African American                                            2
Hispanic or Latino;Asian                                                             2
Hispanic or Latino;American Indian/Native American/Alaska Native;White/Caucasian     1
Asian;White/Caucasian                                                                1
American Indian/Native American/Alaska Native                                        1
White/Caucasian;Multi-Racial                                                         1
Asian;Multi-Racial                                                                   1
Hispanic or Latino;American Indian/Native American/Alaska Native                     1
Name: count, dtype: int64

In [206]:
print("Non-Majors")
print("Shape:", non_majors_cleaned.shape)
print("Columns:", non_majors_cleaned.columns)
print("Unique column names:", non_majors_cleaned.columns.is_unique)
print("Missing values:", non_majors_cleaned.isna().sum())
print("Duplicate rows:", non_majors_cleaned.duplicated().sum())
print("Data types:", non_majors_cleaned.dtypes)
print(non_majors_cleaned["race/ethnicity"].value_counts(dropna=False))

Non-Majors
Shape: (118, 70)
Columns: Index(['which_course_are_you_currently_enrolled_in?',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[professional_development]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[job_displacement]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[relocation]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[it_industry_certifications]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[financial]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[personal_enrichment]',
       'what_motivated_you_to_seek_a_computing_class_at_ccm?_[curiosity]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[open_house]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[instant_decision_day]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[on-campus_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[titan's_tuesday_virtual_information_session]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[women_who_dare]',
       'prior_to_applying_to_college,_did_you_participate_in_any_of_the_following_events_or_activities_at_the_county_college_of_morris_and/or_with_the_department_of_information_technologies,_if_at_all?_[regional_college_fair]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[middle/high_school_computing_related_club]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[computing-related_competitions_(e.g.,_robotics_competition,_lego_competition,_cybersecurity,_programming)]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[afterschool_computing-related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[summer_computing_related_camp/program]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[an_ap_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[a_dual_enrollment_computing_class]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_influence]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[family_or_friend_working_in_the_computing_field]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[high_school_teacher_or_guidance_counselor]',
       'to_what_extent_did_the_following_activities_or_experience_impact_your_decision_to_enroll_in_an_computing_course_at_ccm?_[employer_influence]',
       'how_did_you_hear_about_county_college_of_morris__[ccm_web_site]',
       'how_did_you_hear_about_county_college_of_morris__[billboard]',
       'how_did_you_hear_about_county_college_of_morris__[television]',
       'how_did_you_hear_about_county_college_of_morris__[radio]',
       'how_did_you_hear_about_county_college_of_morris__[social_media]',
       'how_did_you_hear_about_county_college_of_morris__[community_event]',
       'how_did_you_hear_about_county_college_of_morris__[family_member_or_friend]',
       'how_did_you_hear_about_county_college_of_morris__[employer]',
       'how_did_you_hear_about_county_college_of_morris__[current_student]',
       'how_did_you_hear_about_county_college_of_morris__[alumni]',
       'how_did_you_hear_about_county_college_of_morris__[high_school]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[affordable_cost]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[location/convenience]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[choice_of_programs]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[online_offerings]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[family/friend_referral]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[faculty/staff]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[college_reputation]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[scholarships]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[transfer_student]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[small_class_sizes]',
       'to_what_extent_did_the_following_impact_your_decision_to_attend_county_college_of_morris?_[extra_curricula_opportunities]',
       'what_degree_program_are_you_currently_enrolled_in?',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[high_school_guidance_counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_information_technologies_website]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_admissions]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[ccm_advisor/counselor]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[employer]',
       'did_you_receive_information_about_our_computing_course_from_any_of_the_following_sources?_[other]',
       'on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_taking_more_courses_in_computer_science,_information_technology_or_game_development?',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[web_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[cybersecurity]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[app_development]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[data_analytics]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[machine_learning/artificial_intelligence]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[computer_programming]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]',
       'if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]',
       'gender', 'race/ethnicity', 'age'],
      dtype='str')
Unique column names: True
Missing values: which_course_are_you_currently_enrolled_in?                                                                                                  0
what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]                                  0
what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]                                                   0
what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]                                                                    0
what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]                                                                         0
                                                                                                                                            ..
if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]                       0
if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]    0
gender                                                                                                                                       1
race/ethnicity                                                                                                                               0
age                                                                                                                                          0
Length: 70, dtype: int64
Duplicate rows: 0
Data types: which_course_are_you_currently_enrolled_in?                                                                                                  str
what_motivated_you_to_seek_a_computing_class_at_ccm?_[itâ€™s_a_required_class_for_the_degree_iâ€™m_seeking]                                  str
what_motivated_you_to_seek_a_computing_class_at_ccm?_[to_keep_current_in_computing_skills]                                                   str
what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_advancement]                                                                    str
what_motivated_you_to_seek_a_computing_class_at_ccm?_[career_change]                                                                         str
                                                                                                                                            ...
if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[game_design]                       str
if_you_answered_that_you_were_interested_in_taking_more_computing_classes,_which_ones_interest_you_most?_[hardware_installation_&_repair]    str
gender                                                                                                                                       str
race/ethnicity                                                                                                                               str
age                                                                                                                                          str
Length: 70, dtype: object
race/ethnicity
White/Caucasian                                                                                      56
Hispanic or Latino                                                                                   29
Asian                                                                                                 7
Black/African American                                                                                6
Choose not to reply                                                                                   5
Hispanic or Latino;White/Caucasian                                                                    5
American Indian/Native American/Alaska Native;White/Caucasian                                         3
Hispanic or Latino;White/Caucasian;Multi-Racial                                                       3
Native Hawaiian/Other Pacific Islander;White/Caucasian                                                1
Black/African American;White/Caucasian                                                                1
Asian;White/Caucasian                                                                                 1
American Indian/Native American/Alaska Native;Black/African American;White/Caucasian;Multi-Racial     1
Name: count, dtype: int64

## 10 Save the cleaned datasets

Use pandas to save these two files in the `cleaned-data` folder without including the DataFrame index:

- `majors_survey_cleaned.csv`
- `nonmajors_survey_cleaned.csv`

In [207]:
majors_cleaned.to_csv("cleaned-data/majors_cleaned.csv", index=False)
non_majors_cleaned.to_csv("cleaned-data/non_majors_cleaned.csv", index=False)

## 11 Verify the saved files

Use pandas to read both cleaned CSV files back into new DataFrames. Confirm their shape and column names. This verifies that the files were saved correctly.

In [208]:
majors_cleaned = pd.read_csv("cleaned-data/majors_cleaned.csv")
majors_cleaned.shape
majors_cleaned.columns
majors_cleaned.head()

,which_course_are_you_enrolled_in?,how_did_you_hear_about_county_college_of_morris?_[ccm_web_site],how_did_you_hear_about_county_college_of_morris?_[social_media],how_did_you_hear_about_county_college_of_morris?_[community_event],how_did_you_hear_about_county_college_of_morris?_[family_member_or_friend],how_did_you_hear_about_county_college_of_morris?_[current_ccm_student],how_did_you_hear_about_county_college_of_morris?_[ccm_alumni],how_did_you_hear_about_county_college_of_morris?_[high_school_teacher],how_did_you_hear_about_county_college_of_morris?_[high_school_counselor],how_did_you_hear_about_county_college_of_morris?_[in-app_advertisement],...,did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[employer],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[ccm_workforce_development],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[nj_workforce_development_program],did_you_receive_information_about_the_ccm_computing_programs_from_any_of_the_following_sources?_[other],"was_a_computing_major/certificate_your_first_choice,_or_did_you_change_majors_from_a_different_ccm_program?_if_you_changed_majors,_indicate_what_your_first_major_was.","on_a_scale_of_1_to_5,_with_1_being_not_at_all_interested_and_5_being_extremely_interested,_how_interested_are_you_in_taking_more_computing_classes?",please_explain_your_answer_to_the_question_above.__why_or_why_not_would_you_be_interested_in_taking_another_computing_class?,gender,race/ethnicity,age
0,CMP 130 Intro to IT,No,No,No,Yes,No,No,Yes,Yes,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,18 and younger
1,CMP 130 Intro to IT,No,No,Yes,Yes,No,Yes,No,No,No,...,No,Yes,Yes,Don't recall,Criminal Sceince,NaN,NaN,Man,White/Caucasian,35-64
2,CMP 130 Intro to IT,Yes,No,Yes,Yes,No,No,Yes,Yes,No,...,Don't recall,Don't recall,Don't recall,Don't recall,First Choice,NaN,NaN,Man,Multi-Racial,18 and younger
3,CMP 130 Intro to IT,No,No,No,Yes,Yes,No,No,No,No,...,No,No,No,No,Engineering,NaN,NaN,Man,Hispanic or Latino,21-24
4,CMP 130 Intro to IT,No,No,No,Yes,No,No,No,No,No,...,No,No,No,No,First Choice,NaN,NaN,Man,White/Caucasian,19-20

## 12 Final reflection

In your own words, answer the following:

1. What were the most important cleaning decisions?
2. How did the majors and non-majors surveys differ?
3. What information may have been lost during cleaning?
4. What limitations remain in the cleaned datasets?
5. How could the cleaned data support a future recruitment study?

## Final Check

Before submitting:

- Run all cells from top to bottom.
- Correct all errors.
- Make sure outputs are visible.
- Confirm that both cleaned CSV files exist.
- Complete `AI-Use-Report.md`.
- Commit and push the latest work to GitHub.